baseURL = "https://jamesdavidson.xyz/"
defaultContentLanguage = "en"
languageCode = "en"
theme = "gokarna"

# Enable emoji shortcodes
# https://gohugo.io/functions/emojify/
enableEmoji = "true"

# String that appears at the top of the Home page
title = "James Davidson"

# Automatically generate robots.txt
enableRobotsTXT = true

# Syntax highlighting style
pygmentsStyle = "dracula"

# Add a license header to the footer
copyright = "Content is licensed under the [Creative Commons Attribution-NoDerivatives 4.0 International License](http://creativecommons.org/licenses/by-nd/4.0/), unless otherwise specified."

# Disable RSS (broken by Hugo v0.134.x)
disableKinds = [
    "RSS",
    ]

[params]

  avatarURL = "/images/avatar.jpg"
  avatarSize = "size-s"

  showPostsOnHomePage = "recent"

  togglePreviousAndNextButtons = "true"

  # SEO keywords
  metaKeywords = ["linux", "privacy", "cybersecurity"]

  # String that appears on the Home page, below the Title
  description = "The radio presenter with a voice for print"

  # Icons that appear on the Home page, below the Description
  socialIcons = [
    {name = "linkedin", url = "https://www.linkedin.com/in/jamesericdavidson"},
    {name = "codeberg", url = "https://codeberg.org/jamesericdavidson"},
    {name = "github", url = "https://github.com/jamesericdavidson"},
    {name = "protonmail", url = "mailto:james@jamesdavidson.xyz"},
  ]

  # String that appears at the bottom of the Home page
  footer = "James Davidson"

 # Accent color is displayed when you hover over <a> tags
 # Default is #FF4D4D
 # accentColor = "#FF4D4D"

  # Display "back to top" button on posts
  ShowBackToTopButton = true

  # For valid date strings see: https://pkg.go.dev/time#pkg-constants
  dateFormat = "2006-01-02"

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    pre = "<span data-feather='home'></span>"

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
    pre = "<span data-feather='book'></span>"

  [[menu.main]]
    name = "Radio"
    url = "/radio-show-archive/"
    weight = 3
    pre = "<span data-feather='mic'></span>"

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 4
    pre = "<span data-feather='code'></span>"

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 5
    pre = "<span data-feather='tag'></span>"

  [[menu.main]]
    identifier = "LinkedIn"
    weight = 10
    url = "https://www.linkedin.com/in/jamesericdavidson"
    pre = "<span data-feather='linkedin'></span>"

  [[menu.main]]
    identifier = "Codeberg"
    weight = 20
    url = "https://codeberg.org/jamesericdavidson"
    pre = "<span data-feather='code'></span>"

  [[menu.main]]
    identifier = "GitHub"
    weight = 30
    url = "https://github.com/jamesericdavidson"
    pre = "<span data-feather='github'></span>"

  [[menu.main]]
    identifier = "Email"
    weight = 98
    url = "mailto:james@jamesdavidson.xyz"
    pre = "<span data-feather='mail'></span>"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false
