baseURL = "https://jamesdavidson.xyz/"
defaultContentLanguage = "en"
languageCode = "en"
theme = "gokarna"

# String that appears at the top of the Home page
title = "James Davidson"

# Automatically generate robots.txt
enableRobotsTXT = true

# Syntax highlighting style
pygmentsStyle = "vim"

[params]

  showPostsOnHomePage = "recent"

  # SEO keywords
  metaKeywords = ["linux", "privacy", "cybersecurity"]

  # String that appears on the Home page, below the Title
  description = "GNU/Linux, Cyber Security, Digital Privacy and more!"

  # Icons that appear on the Home page, below the Description
  socialIcons = [
    {name = "protonmail", url = "mailto:james@jamesdavidson.xyz"},
    {name = "linkedin", url = "https://www.linkedin.com/in/jamesericdavidson"},
    {name = "gitlab", url = "https://gitlab.com/jamesericdavidson"},
  ]

  # String that appears at the bottom of the Home page
  footer = "James Davidson"

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    pre = "<span data-feather='home'></span>"

  [[menu.main]]
    name = "All Posts"
    url = "/posts/"
    weight = 2
    pre = "<span data-feather='book'></span>"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false
