baseURL = "https://jamesdavidson.xyz/"
defaultContentLanguage = "en"
languageCode = "en"
theme = "gokarna"

# Enable emoji shortcodes
# https://gohugo.io/functions/emojify/
enableEmoji = "true"

# String that appears at the top of the Home page
title = "James Davidson"

# Automatically generate robots.txt
enableRobotsTXT = true

# Syntax highlighting style
pygmentsStyle = "dracula"

[params]

  showPostsOnHomePage = "popular"

  # SEO keywords
  metaKeywords = ["linux", "privacy", "cybersecurity"]

  # String that appears on the Home page, below the Title
  description = "I talk about cybersecurity."

  # Icons that appear on the Home page, below the Description
  socialIcons = [
    {name = "linkedin", url = "https://www.linkedin.com/in/jamesericdavidson"},
    {name = "gitlab", url = "https://gitlab.com/jamesericdavidson"},
    {name = "protonmail", url = "mailto:james@jamesdavidson.xyz"},
  ]

  # String that appears at the bottom of the Home page
  footer = "James Davidson"

[menu]

  [[menu.main]]
    name = "Curriculum Vitae"
    url = "/cv.pdf/"
    weight = 1
    pre = "<span data-feather='file-text'></span>"

  [[menu.main]]
    name = "Software Projects"
    url = "/software-projects/"
    weight = 2
    pre = "<span data-feather='code'></span>"

  [[menu.main]]
    name = "All Posts"
    url = "/posts/"
    weight = 3
    pre = "<span data-feather='book'></span>"

  [[menu.main]]
    name = "Browse Tags"
    url = "/tags/"
    weight = 4
    pre = "<span data-feather='tag'></span>"

  [[menu.main]]
    name = "RSS Feed"
    url = "/index.xml"
    weight = 5
    pre = "<span data-feather='rss'></span>"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false
