baseURL = "https://jamesdavidson.xyz/"
defaultContentLanguage = "en"
languageCode = "en"
theme = "gokarna"

# Enable emoji shortcodes
# https://gohugo.io/functions/emojify/
enableEmoji = "true"

# String that appears at the top of the Home page
title = "James Davidson"

# Automatically generate robots.txt
enableRobotsTXT = true

# Syntax highlighting style
pygmentsStyle = "dracula"

# Add a license header to the footer
copyright = "Content is licensed under the [Creative Commons Attribution-NoDerivatives 4.0 International License](http://creativecommons.org/licenses/by-nd/4.0/), unless otherwise specified."

[params]

  showPostsOnHomePage = "popular"

  # SEO keywords
  metaKeywords = ["linux", "privacy", "cybersecurity"]

  # String that appears on the Home page, below the Title
  description = "Searching for an engaging career in cybersecurity!"

  # Icons that appear on the Home page, below the Description
  socialIcons = [
    {name = "linkedin", url = "https://www.linkedin.com/in/jamesericdavidson"},
    {name = "protonmail", url = "mailto:james@jamesdavidson.xyz"},
    {name = "gitlab", url = "https://gitlab.com/jamesericdavidson"},
    {name = "codeberg", url = "https://codeberg.org/jamesericdavidson"},
    {name = "github", url = "https://github.com/jamesericdavidson"},
  ]

  # String that appears at the bottom of the Home page
  footer = "James Davidson"

  # Use content/_index.md to display content on the homepage
  enableFrontMatter = "true"

[menu]

  [[menu.main]]
    name = "Curriculum Vitae"
    url = "/cv.pdf/"
    weight = 1
    pre = "<span data-feather='file-text'></span>"

  [[menu.main]]
    name = "Software Projects"
    url = "/software-projects/"
    weight = 2
    pre = "<span data-feather='code'></span>"

  [[menu.main]]
    name = "All Posts"
    url = "/posts/"
    weight = 3
    pre = "<span data-feather='book'></span>"

  [[menu.main]]
    name = "Browse Tags"
    url = "/tags/"
    weight = 4
    pre = "<span data-feather='tag'></span>"

  [[menu.main]]
    name = "RSS Feed"
    url = "/index.xml"
    weight = 5
    pre = "<span data-feather='rss'></span>"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
