baseURL = "https://jamesdavidson.xyz/"
defaultContentLanguage = "en"
languageCode = "en"

title = "James Davidson"

theme = "gokarna"

# Automatically generate robots.txt
enableRobotsTXT = true

[menu]

  [[menu.main]]
    identifier = "mail"
    url = "mailto:james@jamesdavidson.xyz"
    weight = 1

    pre = "<span data-feather='mail'></span>"

  [[menu.main]]
    identifier = "gitlab"
    url = "https://gitlab.com/jamesericdavidson"
    weight = 2

    pre = "<span data-feather='gitlab'></span>"

  [[menu.main]]
    identifier = "linkedin"
    url = "https://www.linkedin.com/in/jamesericdavidson/"
    weight = 3
    
    pre = "<span data-feather='linkedin'></span>"

[params]
  # Description to display on homepage
  description = "Linux and Cybersecurity"

  # If you want to display posts on the homepage, the options are
  # "popular" (order posts by weight), "recent" (order posts by date)
  # or "" (do not display, default option)
  showPostsOnHomePage = "recent"

  # Footer text
  footer = "James Davidson"

